# Generated by Django 5.0.2 on 2024-03-28 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pic',
        ),
    ]
