# Generated by Django 5.0.2 on 2024-03-21 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('creditcard', 'CreditCard'), ('cash', 'Cash'), ('cheque', 'cheque')], max_length=100)),
            ],
            options={
                'db_table': 'accounttype',
            },
        ),
        migrations.CreateModel(
            name='CurrencyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'currencytype',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goalname', models.CharField()),
            ],
            options={
                'db_table': 'goal',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(null=True)),
                ('balance', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('accounttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.accounttype')),
                ('currencytype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.currencytype')),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('expDateTime', models.DateField()),
                ('category', models.CharField()),
                ('subCategory', models.CharField()),
                ('transaction_type', models.CharField(choices=[('expense', 'expense'), ('income', 'income')], max_length=50)),
                ('status', models.CharField(choices=[('cleared', 'cleared'), ('uncleared', 'uncleared'), ('void', 'void')], max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.goal')),
            ],
            options={
                'db_table': 'Expense',
            },
        ),
    ]
