# Generated by Django 5.0.2 on 2024-03-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goalname',
            field=models.CharField(max_length=100),
        ),
    ]
