# Generated by Django 5.0.2 on 2024-03-21 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_goal_goalname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expense.goal'),
        ),
    ]
