# Generated by Django 5.0.2 on 2024-03-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_alter_expense_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='day',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='income',
            field=models.FloatField(null=True),
        ),
    ]
